CLASS /s4tax/dal_mkpf DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
    TYPE-POOLS: abap.
    INTERFACES: /s4tax/idal_mkpf.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS /s4tax/dal_mkpf IMPLEMENTATION.
ENDCLASS.
